# Generated by Django 5.1.1 on 2024-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('date_added',)},
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.CharField(default='unknown', max_length=25, verbose_name='User name'),
            preserve_default=False,
        ),
    ]
